### ISSUE TITLE
Subtitle syncing

### ISSUE THREAD

**Issue by mgoral** [mgoral/subconvert#55]
Add syncing subtitles with two time points e.g. selectable from movie timeline in gui, or by switches in cli:

```
subconvert --sync-start=xxx --sync-end=xxx
```

**TODO**

- [x] Select and add sync points
- [x] Apply sync points via a Command
- [x] Remove sync points - maybe something more user friendly than 2-step selecting a sync point and clicking "remove" button.
- [x] Do not allow repeating same subtitles on sync list
- [x] Do not allow repeating same sync times on sync list
- [x] Do not allow opening two sync windows for the same file
- [x] Auto remove sync points when user removes corresponding subtitle (subscribe for and handle correct signals)
- [x] Change sync point's subtitle number when user inserts or removes a subtitle before it (auto decrement)
- [x] Handle `fileChanged` signal (emitted by `ChangeData` command)
- [x] CLI syncing (see comments below for syntax proposition)
- [x] Documentation of syncing
- [x] GUI offsetting
- [x] CLI offsetting

**Comment by mgoral** [comment]
GUI: separate modal window with passed video player and current editor tab. Something like a big "+" button, which adds synchronization points constructed from currently selected subtitle and video position.

Arbitrary number of sync points can be added (so it must support some kind of scrollable list, however only subtitle excerpt and new start time should be displayed). List elements should be removable.

Clicking "OK" calls a callback on editor tab; "Cancel" simply closes this window.

**Comment by mgoral** [comment]
It works great on `feat/sync` branch, although only unsafe adding sync points is implemented. :)

**Comment by mgoral** [comment]
It should be safe now.

CLI and docs left.

**Comment by mgoral** [comment]
CLI proposition:

There should be a single `--sync` option, which should accept parsable string. That string is a list of subtitle numbers, either positive (counted from the beginning) or negetive (counted from the end) followed by a colon (or some other sign) and then time specification:

* `+3s` adds 3 seconds to pointed subtitle. Accepted time specifiers: `h`, `m`, `s`, `ms`.
* `-3s` removes 3 seconds. Reports an error when result would be less than 0.
* `1h10s` sets subtitle to 1 hour and 10 seconds.

Sync points are separated by a comma, possibly surronuded by any number of whitespaces (they should be simply stripped)

Examples:

```
$ subconvert -c blah.txt --sync="1:+15s,-1:-10s"
$ subconvert -c blah.txt --sync="1:12s,2:17s,-1:1m12s123ms"
```

Errorneous examples:

```
// second sync point lower than the first one
$ subconvert -c blah.txt --sync="1:5s,-1:1s"
```
